### ISSUE TITLE
where would i get converted file (hbs file)

### ISSUE THREAD

**Issue by rahul9874563210** [kesla/jade-to-handlebars#1]

**Comment by kesla** [comment]
it'll get created next to your .jade-file. Is it not working for you?

**Comment by kesla** [comment]
@rahul9874563210 hey, any more information you get give?

**Comment by rahul9874563210** [comment]
@kesla  actually in my current project i started with jade as template engine but as soon as the project gets large it is very difficult to mentain the project specially for designer who comes from a html world .
so the problem was that i wanted to convert all my jade files into hbs .

but now i moved to swig .
Extremely  sorry for the late reply
